// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9jRXo7P92ZlU2GWvK73NZV8Axsxva8ew',
    appId: '1:423642543061:web:dff8fc6c373047cab4c35c',
    messagingSenderId: '423642543061',
    projectId: 'orientis-8d0ec',
    authDomain: 'orientis-8d0ec.firebaseapp.com',
    storageBucket: 'orientis-8d0ec.firebasestorage.app',
    measurementId: 'G-9VD1L2ZJJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-5OnDfRNWhCi0DzBvQXW9FK7mDEuVgEI',
    appId: '1:423642543061:android:6e8026298b576edbb4c35c',
    messagingSenderId: '423642543061',
    projectId: 'orientis-8d0ec',
    storageBucket: 'orientis-8d0ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ci5d5iVPSWSkINJNHqDASyTLRYcrPQQ',
    appId: '1:423642543061:ios:5e896559507ab9a8b4c35c',
    messagingSenderId: '423642543061',
    projectId: 'orientis-8d0ec',
    storageBucket: 'orientis-8d0ec.firebasestorage.app',
    iosBundleId: 'com.app.orienty',
  );
}
